# Generated by Django 3.2.9 on 2022-05-24 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In_Transit'), ('DELIVERED', 'delivered')], default='PENDING', max_length=25)),
                ('start_at', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField()),
                ('target_signature_counter', models.IntegerField()),
                ('contact_info', models.CharField(max_length=300)),
                ('organiser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
