# Generated by Django 3.2.8 on 2022-05-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='organiser_id',
            field=models.IntegerField(),
        ),
    ]
